development:
  host: localhost
  username: guest
  password: guest
  port: 5672
  vhost: /


test:
  host: localhost
  username: guest
  password: guest
  port: 5672
  vhost: /


production:
  host: lemur.cloudamqp.com
  username: fqylgoyl
  password: QUI6dCD7XopqkLQ0kFJDwvBeGm6hfS3Y
  port: 5672
  vhost: fqylgoyl
