development:
  outbound:
    accounts:
      omnitest:
        delivery_method: smtp
        from:      do-not-reply@parkersu.com
        reply_to:      do-not-reply@parkersu.com
        smtp_settings:
          address:   smtp.gmail.com
          port:      587
          domain:    gmail.com
          user_name: aaron@buildit.io
          password:  CrossFit
          authentication: plain
          enable_starttls_auto: true
      # omnitest:
      #   address:   smtp.gmail.com
      #   default:   true
      #   port:      587
      #   domain:    gmail.com
      #   user_name: omni-test@buildit.io
      #   password:  TunaCasserole2013
      #   authentication: plain
      #   enable_starttls_auto: true
      # omnitest:
      #   address:   smtp.gmail.com
      #   default:   true
      #   port:      587
      #   domain:    gmail.com
      #   user_name: aaron@buildit.io
      #   password:  CrossFit
      #   authentication: plain
      #   enable_starttls_auto: true
  inbound:
    accounts:
      bigdump:
        default:  true
        provider: pop3
        server:   pop.gmail.com
        port:     995
        username: user@gmail.com
        password: pwd
production:
  outbound:
    accounts:
      omniprod:
        from:      do-not-reply@parkersu.com
        reply_to:  do-not-reply@parkersu.com
        address:   smtp.gmail.com
        default:   true
        port:      587
        domain:    gmail.com
        user_name: aaron@buildit.io
        password:  CrossFit
        authentication: plain
        enable_starttls_auto: true
  inbound:
    accounts:
      bigdump:
        default:  true
        provider: pop3
        server:   pop.gmail.com
        port:     995
        username: user@gmail.com
        password: pwd
