# DEFAULT RDBMS: Connection Details
#---------------------------------------------------

development:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: true
  database: omni_development
  pool: 20
  username: root
  password:
  wait_timeout: 2147483
  host: 127.0.0.1

production:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: true
  database: omni_db
  pool: 20
  username: root
  password: password103
  wait_timeout: 2147483
  host: http://omni.che7o4j7ujdi.us-east-1.rds.amazonaws.com/

# MARK RDBMS: Connection Details
#---------------------------------------------------

ndb_development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: ndb_psu
  pool: 20
  username: root
  password:
  wait_timeout: 2147483
  host: 10.0.1.15

ndb_production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: ndb_psu
  pool: 20
  username: root
  password:
  wait_timeout: 2147483
  host: 10.0.1.15

mark_production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: mark_development
  pool: 20
  username: root
  password:
  wait_timeout: 2147483
  host: 127.0.0.1

mark_development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: mark_development
  pool: 20
  username: root
  password:
  wait_timeout: 2147483
  host: 127.0.0.1

# RMS RDBMS: Connection Details
#---------------------------------------------------

rms_development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: rms_development
  pool: 20
  username: root
  password:
  wait_timeout: 2147483
  host: 127.0.0.1

rms_production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: rms_development
  pool: 20
  username: root
  password:
  wait_timeout: 2147483
  host: 127.0.0.1


