
development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    min_memory: 512M
    max_memory: 1G
    path: '/solr/omni_dev'

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    min_memory: 512M
    max_memory: 1G
    path: '/solr/omni_test'

production:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    min_memory: 512M
    max_memory: 1G
    path: '/solr/omni'

