
production:
  solr:
    hostname: localhost
    port: 9091
    log_level: WARNING
    min_memory: 512M
    max_memory: 2048M
    path: '/solr/omni'

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    min_memory: 512M
    max_memory: 1G
    path: '/solr/omni'

production:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    min_memory: 512M
    max_memory: 1G

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING

