
development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    min_memory: 512M
    max_memory: 1G
    path: '/solr/omni'

production:
  solr:
    hostname: 162.243.108.76
    port: 8983
    log_level: INFO
    min_memory: 512M
    max_memory: 1G
    path: '/solr/omni'

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING

