Buildit::Lookup.create(:lookup_id => 'C72A35DA038911APPROVEDPROJECTION', :code => 'APPROVED_PROJECTION', :default_text => 'Approved Projection', :category => 'ALLOCATION_FORMULA', :position => 1)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911E398B42PROJECTION1', :code => 'PROJECTION_1_UNITS', :default_text => 'Projection 1', :category => 'ALLOCATION_FORMULA', :position => 2)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911E398B42PROJECTION2', :code => 'PROJECTION_2_UNITS', :default_text => 'Projection 2', :category => 'ALLOCATION_FORMULA', :position => 3)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911E398B42PROJECTION3', :code => 'PROJECTION_3_UNITS', :default_text => 'Projection 3', :category => 'ALLOCATION_FORMULA', :position => 4)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911E398B42PROJECTION4', :code => 'PROJECTION_4_UNITS', :default_text => 'Projection 4', :category => 'ALLOCATION_FORMULA', :position => 5)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911PROJECTIONFORECAST', :code => 'LAST_FORECAST_UNITS', :default_text => 'Projection Forecast', :category => 'ALLOCATION_FORMULA', :position => 6)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911E398B428CFEBTSNEED', :code => 'BTS_NEED', :default_text => 'BTS Need', :category => 'ALLOCATION_FORMULA', :position => 7)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911PURCHASEALLOCATION', :code => 'ALLOCATED_UNITS', :default_text => 'Purchase Allocation', :category => 'ALLOCATION_FORMULA', :position => 8)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911EAPPORTIONTOSTORES', :code => 'APPORTION_TO_STORES', :default_text => 'Apportion To Stores', :category => 'EXCESS_SUPPLY_OPTION', :position => 1)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911E3LEAVEINWAREHOUSE', :code => 'LEAVE_IN_WAREHOUSE', :default_text => 'Leave In Warehouse', :category => 'EXCESS_SUPPLY_OPTION', :position => 2)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911APPORTIONBYPERCENT', :code => 'APPORTION_BY_PERCENT', :default_text => 'Apportion By Percent', :category => 'EXCESS_DEMAND_OPTION', :position => 1)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911EFILLLARGESTDEMAND', :code => 'FILL_LARGEST_DEMAND', :default_text => 'Fill Largest Demand', :category => 'EXCESS_DEMAND_OPTION', :position => 2)
Buildit::Lookup.create(:lookup_id => 'C72A35DA038911E398B428CFE914NONE', :code => 'NONE', :default_text => 'None', :category => 'ROUNDING_OPTION', :position => 1)
Buildit::Lookup.create(:lookup_id => 'IIII8902XXX8XODEHU231PURCHASECMT', :code => 'CMT', :default_text => "CMT", :category => 'PURCHASE_TYPE', :position => 1)
Buildit::Lookup.create(:lookup_id => 'IIII8902XXX8XODEHU231PURCHASEDDP', :code => 'DDP', :default_text => "DDP", :category => 'PURCHASE_TYPE', :position => 2)
Buildit::Lookup.create(:lookup_id => 'AOEU8902XXX8XODEHUPURCHASEMANUAL', :code => 'MANUAL', :default_text => "Manual", :category => 'PURCHASE_SOURCE', :position => 1)
Buildit::Lookup.create(:lookup_id => 'AOEU8902XXX8XODEHUWEIGHTEDDEMAND', :code => 'WEIGHTED_DEMAND', :default_text => "Weighted Sales", :category => 'FORECAST_CALCULATION', :position => 1)

