Buildit::Sequence.create(:sequence_code => 'ADJUSTMENT_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'ADJUSTMENT_NBR').first
Buildit::Sequence.create(:sequence_code => 'AREA_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'AREA_NBR').first
Buildit::Sequence.create(:sequence_code => 'ALLOCATION_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'ALLOCATION_NBR').first
Buildit::Sequence.create(:sequence_code => 'ALLOCATION_DETAIL_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'ALLOCATION_DETAIL_NBR').first
Buildit::Sequence.create(:sequence_code => 'BIN_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'BIN_NBR').first
Buildit::Sequence.create(:sequence_code => 'BOM_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'BOM_NBR').first
Buildit::Sequence.create(:sequence_code => 'CLASSIFICATION_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'CLASSIFICATION_NBR').first
Buildit::Sequence.create(:sequence_code => 'COLOR_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'COLOR_NBR').first
Buildit::Sequence.create(:sequence_code => 'COMPANY_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'COMPANY_NBR').first
Buildit::Sequence.create(:sequence_code => 'CONTAINER_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'CONTAINER_NBR').first
Buildit::Sequence.create(:sequence_code => 'CUSTOMER_ACCOUNT_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'CUSTOMER_ACCOUNT_NBR').first
Buildit::Sequence.create(:sequence_code => 'CUSTOMER_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'CUSTOMER_NBR').first
Buildit::Sequence.create(:sequence_code => 'CUSTOMER_ORDER_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'CUSTOMER_ORDER_NBR').first
Buildit::Sequence.create(:sequence_code => 'DEPARTMENT_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'DEPARTMENT_NBR').first
Buildit::Sequence.create(:sequence_code => 'DISTRICT_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'DISTRICT_NBR').first
Buildit::Sequence.create(:sequence_code => 'EMPLOYEE_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'EMPLOYEE_NBR').first
Buildit::Sequence.create(:sequence_code => 'LOCATION_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'LOCATION_NBR').first
Buildit::Sequence.create(:sequence_code => 'ORDER_LINE_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'ORDER_LINE_NBR').first
Buildit::Sequence.create(:sequence_code => 'PAYMENT_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'PAYMENT_NBR').first
Buildit::Sequence.create(:sequence_code => 'PICK_TICKET_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'PICK_TICKET_NBR').first
Buildit::Sequence.create(:sequence_code => 'PRODUCT_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'PRODUCT_NBR').first
Buildit::Sequence.create(:sequence_code => 'PROGRAM_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'PROGRAM_NBR').first
Buildit::Sequence.create(:sequence_code => 'PROJECTION_DETAIL_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'PROJECTION_DETAIL_NBR').first
Buildit::Sequence.create(:sequence_code => 'PURCHASE_ALLOCATION_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'PURCHASE_ALLOCATION_NBR').first
Buildit::Sequence.create(:sequence_code => 'STOCK_LEDGER_ACTIVITY_LOG_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'STOCK_LEDGER_ACTIVITY_LOG_NBR').first
Buildit::Sequence.create(:sequence_code => 'PURCHASE_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'PURCHASE_NBR').first
Buildit::Sequence.create(:sequence_code => 'PURCHASE_DETAIL_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'PURCHASE_DETAIL_NBR').first
Buildit::Sequence.create(:sequence_code => 'RECEIPT_ALLOCATION_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'RECEIPT_ALLOCATION_NBR').first
Buildit::Sequence.create(:sequence_code => 'RECEIPT_LINE_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'RECEIPT_LINE_NBR').first
Buildit::Sequence.create(:sequence_code => 'RECEIPT_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'RECEIPT_NBR').first
Buildit::Sequence.create(:sequence_code => 'REGION_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'REGION_NBR').first
Buildit::Sequence.create(:sequence_code => 'SCHOOL_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'SCHOOL_NBR').first
Buildit::Sequence.create(:sequence_code => 'SIZE_GROUP_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'SIZE_GROUP_NBR').first
Buildit::Sequence.create(:sequence_code => 'SIZE_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'SIZE_NBR').first
Buildit::Sequence.create(:sequence_code => 'SKU_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'SKU_NBR').first
Buildit::Sequence.create(:sequence_code => 'STYLE_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'STYLE_NBR').first
Buildit::Sequence.create(:sequence_code => 'SUBCLASS_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'SUBCLASS_NBR').first
Buildit::Sequence.create(:sequence_code => 'SUPPLIER_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'SUPPLIER_NBR').first
Buildit::Sequence.create(:sequence_code => 'TERMINAL_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'TERMINAL_NBR').first
Buildit::Sequence.create(:sequence_code => 'TILL_ACTIVITY_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'TILL_ACTIVITY_NBR').first
Buildit::Sequence.create(:sequence_code => 'TILL_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'TILL_NBR').first
Buildit::Sequence.create(:sequence_code => 'TRANSFER_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'TRANSFER_NBR').first
Buildit::Sequence.create(:sequence_code => 'VOUCHER_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'VOUCHER_NBR').first
Buildit::Sequence.create(:sequence_code => 'WORK_ORDER_NBR', :padding => 3, :value => 1000) unless Buildit::Sequence.where(:sequence_code => 'WORK_ORDER_NBR').first

