Omni::AllocationProfile.delete_all
Omni::AllocationProfile.create!([
  {allocation_profile_id: "8A0B7946BF8311E3BF5320C9D047DD15", display: "default profile", description: "default system profile to use", allocation_formula: "DIVIDE_EQUALLY", percent_to_allocate: "80.0", need_adjustment_percent: nil, excess_demand_option: "APPORTION_BY_PERCENT", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: false},
  {allocation_profile_id: "913BB680231211E3PROJECTION1UNITS", display: "projection 1 units profile", description: nil, allocation_formula: "PROJECTION_1_UNITS", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "FILL_LARGEST_DEMAND", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "913BB680231211E3PROJECTION2UNITS", display: "projection 2 units profile", description: nil, allocation_formula: "PROJECTION_2_UNITS", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "FILL_LARGEST_DEMAND", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "913BB680231211E3PROJECTION3UNITS", display: "projection 3 units profile", description: nil, allocation_formula: "PROJECTION_3_UNITS", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "FILL_LARGEST_DEMAND", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "913BB680231211E3PROJECTION4UNITS", display: "projection 4 units profile", description: nil, allocation_formula: "PROJECTION_4_UNITS", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "FILL_LARGEST_DEMAND", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "913BB680231211XXXXXBTSDEMANDWHSE", display: "last forecast units with allocate by demand and warehouse", description: nil, allocation_formula: "LAST_FORECAST_UNITS", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "FILL_LARGEST_DEMAND", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "913BB680231XXPURCHASEALLOCATIONS", display: "allocated units profile", description: nil, allocation_formula: "PURCHASE_ALLOCATION", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "FILL_LARGEST_DEMAND", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "913BB680231XXXAPPROVEDPROJECTION", display: "approve projection units profile", description: nil, allocation_formula: "APPROVED_PROJECTION", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "FILL_LARGEST_DEMAND", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "913BB680231XXXXLASTFORECASTUNITS", display: "last forecast units profile", description: nil, allocation_formula: "LAST_FORECAST_UNITS", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "FILL_LARGEST_DEMAND", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "LASTFORECASTBYPERCENTINWAREHOUSE", display: "last forecast_units with allocate by percent and leave in warehouse", description: nil, allocation_formula: "LAST_FORECAST_UNITS", percent_to_allocate: "80.0", need_adjustment_percent: nil, excess_demand_option: "APPORTION_BY_PERCENT", excess_supply_option: "LEAVE_IN_WAREHOUSE", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "LASTXFORECASTXXXDIVIDEEQUALLY123", display: "divide equally - no source needed, apportion the units equally amongst the stores", description: nil, allocation_formula: "DIVIDE_EQUALLY", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "", excess_supply_option: "DIVIDE_EQUALLY", rounding_option: "NONE", is_destroyed: nil},
  {allocation_profile_id: "XXXXLASTFORECASTBYPERCENTTOSTORE", display: "last forecast_units with allocate by percent to store", description: nil, allocation_formula: "LAST_FORECAST_UNITS", percent_to_allocate: "100.0", need_adjustment_percent: nil, excess_demand_option: "APPORTION_BY_PERCENT", excess_supply_option: "APPORTION_TO_STORES", rounding_option: "NONE", is_destroyed: nil}
])
